### ISSUE TITLE
[LND] [LNU] As NEAR I want to present learning materials with engaging UX so new users and devs join NEAR right away

### ISSUE THREAD

**Issue by almal** [near/learn#6]
**ToDo:**

- [x] WordPress website with guides
- [x] Login with NEAR
- [x] Integrate docs.near repo for easy reference
- [x] Tech writer for Guides
- [ ] Short branded videos for Guides
- [ ] UX improvement
